const mongoose=require("mongoose");
const requestPollSchema= mongoose.Schema({
    heading:{
        type:String,
        required:true
    },
    detail:{
        type:String,
        required:true
    },
    imageUrl:{
        type:String,
        required:true
    },
    authorId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true
    },
    pollId:{
        type:mongoose.Schema.Types.ObjectId
    },
    isPublished:{
        type:Boolean,
        default:false
    },
    isActive:{
        type:Boolean,
        default:false
    }
});
module.exports=mongoose.model("requestPoll",requestPollSchema);